<<<<<<< HEAD
version: "3.7"
=======
>>>>>>> d9780fe (ci: update files)
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: finance-api
    ports:
<<<<<<< HEAD
      - "8080:8080"
=======
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_PATH=/data/finance.db
      - WORKERS=5
    volumes:
      - db-data:/data

volumes:
  db-data:
>>>>>>> d9780fe (ci: update files)
